name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    environment: docker
    steps:
    - uses: actions/checkout@v3
    
    - name: login Docker image
      run: |
          # 登录阿里云镜像仓库
          docker login --username=393497238@qq.com --password=${{ secrets.ALI_DOCKER_PASSWORD }} registry.us-west-1.aliyuncs.com     
        
    - name: Build the Docker image
      run: |
          cd services/AUTOMATIC1111
          DOCKER_BUILDKIT=1 docker build . --file Dockerfile --tag registry.us-west-1.aliyuncs.com/syai/stable_webui:latest
          
    - name: Push Docker image
      run: | 
          docker push registry.us-west-1.aliyuncs.com/syai/stable_webui:latest
 
